name: "Integration"
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  soundness:
    name: Soundness Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Bootstrap Mint
        uses: irgaly/setup-mint@v1

      - name: Run soundness
        run: |
          scripts/soundness.sh
          exit $(git status --porcelain | wc -l)

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        swift: [latest]

    steps:
      - name: Install Swift
        uses: vapor/swiftly-action@v0.1
        with:
          toolchain: ${{ matrix.swift }}

      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Cache Swift PM
        uses: actions/cache@v4.0.2
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.swift }}-spm-${{ hashFiles('Package.swift') }}
          restore-keys: ${{ runner.os }}-${{ matrix.swift }}-spm-

      - name: Resolve Swift dependencies
        run: swift package resolve

      - name: Run Unit Tests
        run: swift test --parallel

  cli-test:
    name: CLI Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        swift: [latest]

    steps:
      - name: Install Swift
        uses: vapor/swiftly-action@v0.1
        with:
          toolchain: ${{ matrix.swift }}

      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Cache Swift PM
        uses: actions/cache@v4.0.2
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.swift }}-spm-${{ hashFiles('Package.swift') }}
          restore-keys: ${{ runner.os }}-${{ matrix.swift }}-spm-

      - name: Resolve Swift dependencies
        run: swift package resolve

      - name: Build CLI
        run: swift build -c release

      - name: Generate migration files
        run: |
          mkdir ${{ runner.temp }}/migrations
          ./.build/release/chinchilla generate -m ${{ runner.temp }}/migrations --log trace cli_test
          ls -lah ${{ runner.temp }}/migrations
